### ISSUE TITLE
Review TODO list

### ISSUE THREAD

**Issue by KamilSJaron** [KamilSJaron/genomic-features-of-parthenogenetic-animals#26]
This list is prepared for getting reviews and needs to be updated accordingly once we get them. Right now it contains tiny things that don't need to be perfect for the first submission.

**writing**

- [x] mention in methods how we detected rotifer divergence of homoeologs!
- [ ] Replace Figure 1 by Supplementary Figure 1 (with references)
- [ ] make heterozygosity figure without hybrid origin categorization
- [x] verify that all first instance of _latin_ Genus names are not abbreviated!
- [x] write a caption to Supplementary Table 4
- [x] add KAT picture to Supplementary material of rotifer (do 4x4 panel figure - 2 genomescope models, smudgeplot, KAT)

**computing**

- [ ] linked HGT with SwissProt database

**Comment by KamilSJaron** [comment]
JOH TODO:

- [ ] take care of individual comments on the text (comments directly in the google docs)
- [ ] Please clarify why you infer that _Folsomia_ has terminal fusion. The Riparbelli reference does not state that explicitly. I am no expert on these matters, but from what I can gather from that paper, it seems that Folsomia only goes through meiosis I. (reads as "Does Folsomia do a terminal fusion?")
- [ ] caption to Supplementary Table 4 (@reubwn). Comment by r#2: Supplementary table 4 needs explanation. Neither the column names, nor the entries in "notes" are intelligible. I was interested to see what the origin of the high number of HGT sequences mentioned in line 585 would be (could they be derived from endosymbionts - in which case they should trace to probably trace to particular groups of bacteria), but I couldn' make much sense of the output.

Reviewer 2 comments:
- [ ]  I would address comparisons between previous and standardized framework in a supplementary section, to focus in the main manuscript only on the results obtained by the standardized framework.

**Comment by KamilSJaron** [comment]
Accepted
